import { test, expect } from '@playwright/test';

// Ticket #5800
test('Handschriften', async ({ page }) => {
    await page.goto('find/opac/id/HS00000010');
    await expect(page.locator('#detail')).toContainText('Medienart');
    await expect(page.locator('#detail')).toContainText('Handschriften');
    await expect(page.locator('#detail')).toContainText('Gattung');
    await expect(page.locator('#detail')).toContainText('Briefe');
    await expect(page.locator('#detail')).toContainText('VON');
    await expect(page.locator('#detail').locator('a[href*="find/opac/id/PE00051974"]')).toContainText('Uhland, Emilie (1799-1881) [Verfasser/in]');
    await expect(page.locator('#detail')).toContainText('AN');
    await expect(page.locator('#detail').locator('a[href*="find/opac/id/PE00051979"]')).toContainText('Meyer, Marie [Adressat/in]');
    await expect(page.locator('#detail')).toContainText('Entstehungszeit');
    await expect(page.locator('#detail')).toContainText('02.07.1865');
    await expect(page.locator('#detail')).toContainText('Entstehungsort');
    await expect(page.locator('#detail')).toContainText('Tübingen');
    await expect(page.locator('#detail')).toContainText('Umfang, Beilagen');
    await expect(page.locator('#detail')).toContainText('2 Bl.');
    await expect(page.locator('#detail')).toContainText('Sprache');
    await expect(page.locator('#detail')).toContainText('Deutsch');
    await expect(page.locator('#detail')).toContainText('Bestandssignatur');
    await expect(page.locator('#detail').locator('a[href*="find/opac/id/BF00000009"]')).toContainText('A:Uhland, Ludwig');
    await expect(page.locator('#detail')).toContainText('Zugangsnummer');
    await expect(page.locator('#detail')).toContainText('HS.1998.0111.00005');
    await expect(page.locator('#detail')).toContainText('Mediennummer');
    await expect(page.locator('#detail')).toContainText('HS000000109');
    await expect(page.locator('#detail')).toContainText('Benutzung');
    await expect(page.locator('#detail')).toContainText('Benutzung nur bedingt möglich!Nur mit Einverständnis der beteiligten Personen ausleihbar!');
    await expect(page.locator('#detail')).toContainText('In Bestandsübersicht zeigen');
    await expect(page.locator('#detail')).toContainText('Uhland, Ludwig (1787-1862)');
    await expect(page.locator('#detail')).toContainText('Teilnachlass, Handschriften [A:Uhland, Ludwig]');
});

test('Bilder und Objekte', async ({ page }) => {
    await page.goto('find/opac/id/BI00000010');
    await expect(page.locator('#content-area')).toContainText('André, Holger');
    await expect(page.locator('#content-area')).toContainText('1995');
    await expect(page.locator('#content-area')).toContainText('Inventarnummer: B 1999.0010');
    await expect(page.locator('#detail')).toContainText('Medienart');
    await expect(page.locator('#detail')).toContainText('Bilder und Objekte');
    await expect(page.locator('#detail')).toContainText('Objekttyp');
    await expect(page.locator('#detail')).toContainText('Photographie');
    await expect(page.locator('#detail')).toContainText('Titel');
    await expect(page.locator('#detail')).toContainText('Portrait Rafik Schami');
    await expect(page.locator('#detail')).toContainText('Person');
    await expect(page.locator('#detail').locator('a[href*="find/opac/id/PE00004570"]')).toContainText('Schami, Rafik (1946-) [Dargestellte Person allein]');
    await expect(page.locator('#detail').locator('a[href*="find/opac/id/PE00053129"]')).toContainText('André, Holger [Urheber/in]');
    await expect(page.locator('#detail')).toContainText('Entstehungszeit');
    await expect(page.locator('#detail')).toContainText('1995');
    await expect(page.locator('#detail')).toContainText('Bezeichnung');
    await expect(page.locator('#detail')).toContainText('Rückseite mit Aufkleber des Photographen');
    await expect(page.locator('#detail')).toContainText('Technik');
    await expect(page.locator('#detail')).toContainText('Farbphoto. Vergrößerung auf Kunststoffpapier');
    await expect(page.locator('#detail')).toContainText('Maße [in cm]');
    await expect(page.locator('#detail')).toContainText('18,2 (Höhe) x 12,7 (Breite)');
    await expect(page.locator('#detail')).toContainText('Inventarnummer');
    await expect(page.locator('#detail')).toContainText('B 1999.0010');
    await expect(page.locator('#detail')).toContainText('Erwerbungsnummer');
    await expect(page.locator('#detail')).toContainText('BI.1999.0003');
    await expect(page.locator('#detail')).toContainText('Benutzung');
    await expect(page.locator('#detail')).toContainText('Am Standort');
});

test('AK', async ({ page }) => {
    await page.goto('find/opac/id/AK00000010');
    await expect(page.locator('#content-area')).toContainText('Finck, Adrien');
    await expect(page.locator('#content-area')).toContainText('Salzburg : Müller, 1992 - 188 Seiten');
    await expect(page.locator('#detail')).toContainText('Medium');
    await expect(page.locator('#detail')).toContainText('Buch');
    await expect(page.locator('#detail')).toContainText('Titel');
    await expect(page.locator('#detail')).toContainText('Antworten auf Georg Trakl / hrsg. von Adrien Finck ...');
    await expect(page.locator('#detail')).toContainText('Beteiligt');
    await expect(page.locator('#detail').locator('a[href*="find/opac/id/PE00000003"]')).toContainText('Finck, Adrien (1930-2008) [Herausgeber]');
    await expect(page.locator('#detail')).toContainText('Erschienen');
    await expect(page.locator('#detail')).toContainText('Salzburg : Müller, 1992');
    await expect(page.locator('#detail')).toContainText('Umfang');
    await expect(page.locator('#detail')).toContainText('188 Seiten');
    await expect(page.locator('#detail')).toContainText('ISBN');
    await expect(page.locator('#detail')).toContainText('3-7013-0839-X');
    await expect(page.locator('#detail')).toContainText('Teil von');
    await expect(page.locator('#detail').locator('a[href*="find/opac/id/AK00000007"]')).toContainText('Trakl-Studien; 18');
    await expect(page.locator('#detail')).toContainText('Sprache');
    await expect(page.locator('#detail')).toContainText('Deutsch');
    await expect(page.locator('#detail')).toContainText('Inhalt');
    await expect(page.locator('#detail').locator('a[href*="find/opac/id/SE00026756"]')).toContainText('Trakl, Georg / A1.3 Sammelwerke');
    await expect(page.locator('#detail')).toContainText('Prosa');
    await expect(page.getByRole('term')).toContainText('Beziehungen');
    await expect(page.getByRole('definition')).toContainText('Enthaltene Beiträge (');
    await expect(page.locator('#detail').locator('.dd-').locator('a')).toBeVisible();
});

test('BF', async ({ page }) => {
    await page.goto('find/opac/id/BF00000010');
    await expect(page.locator('#content-area')).toContainText('Ackerknecht, Erwin');
    await expect(page.locator('#content-area')).toContainText('2 Kästen');
    await expect(page.locator('#detail')).toContainText('Medienart');
    await expect(page.locator('#detail')).toContainText('Gedrucktes');
    await expect(page.locator('#detail')).toContainText('Bestandsart');
    await expect(page.locator('#detail')).toContainText('Nachlass , Geschlossener Bestand der Mediendokumentation');
    await expect(page.locator('#detail')).toContainText('Bestandsbildner');
    await expect(page.locator('#detail').locator('a[href*="find/opac/id/PE00046925"]')).toContainText('Ackerknecht, Erwin (1880-1960)');
    await expect(page.locator('#detail')).toContainText('Sammlung');
    await expect(page.locator('#detail')).toContainText('Mediendokumentation');
    await expect(page.locator('#detail')).toContainText('Signatur');
    await expect(page.locator('#detail')).toContainText('H:Ackerknecht, Erwin');
    await expect(page.locator('#detail')).toContainText('Umfang');
    await expect(page.locator('#detail')).toContainText('2 Kästen');
    await expect(page.locator('#detail')).toContainText('Inhaltsangabe');
    await expect(page.locator('#detail')).toContainText('Texte von und über Erwin Ackerknecht, sonstige Texte');
    await expect(page.locator('#detail')).toContainText('Mediennummer');
    await expect(page.locator('#detail')).toContainText('BF000000109');
    await expect(page.locator('#detail')).toContainText('Benutzungshinweis');
    await expect(page.locator('#detail')).toContainText('Magazin Fellbach - Bitte 2 Wochen im Voraus bestellen! . benutzbar');
    await expect(page.locator('#detail')).toContainText('Ordnung');
    await expect(page.locator('#detail')).toContainText('vorgeordnet (2 Kästen)');
    await expect(page.locator('#detail')).toContainText('In Bestandsübersicht zeigen');
    await expect(page.locator('#detail')).toContainText('A -> Ackerknecht, Erwin (1880-1960) -> Nachlass, Mediendokumentation [H:Ackerknecht, Erwin]');
});

test('Mertens-Suche rechter Bereich', async ({ page }) => {
    await page.goto('find/opac/id/AK01779681');
    await expect(page.locator('.ctg-facet-colum')).toContainText('Vom selben Verfasser / Urheber');
    await expect(page.locator('.ctg-facet-colum')).toContainText('Ähnliche Themen');
    await page.goto('find/opac/id/AK01279668');
    await expect(page.locator('.ctg-facet-colum')).toContainText('Vom selben Verfasser / Urheber');
    await expect(page.locator('.ctg-facet-colum')).toContainText('Vom selben Bestandsbildner');
    await page.goto('find/opac/id/BI00008813');
    await expect(page.locator('.ctg-facet-colum')).toContainText('Vom selben Künstler');
    await expect(page.locator('.ctg-facet-colum')).toContainText('Ähnliche Motive');
    await page.goto('find/opac/id/HS01159739');
    await expect(page.locator('.ctg-facet-colum')).toContainText('Vom selben Bestandsbildner');
    await page.goto('find/opac/id/BF00000001');
    await expect(page.locator('.ctg-facet-colum')).toContainText('Vom selben Bestandsbildner');
});
